In [1]:
import numpy as np
import pyarrow as pa
import h5py
np.random.seed(0)

In [143]:
def create_dataset(N : int):
    output = []
    for i in range(N):
        text1 = "Foto di una nebulosa"
        text2 = "Foto infrarossi di una nebulosa"
        image1 = np.random.rand(3,125,125)
        image2 = np.random.rand(3,125,125)
        image3 = np.random.rand(3,125,125)
        shape = (3,125,125)
       
        
        bb1 = np.random.rand(4)
        bb2 = np.random.rand(4)
        bb3 = np.random.rand(4)
        bb4 = np.random.rand(4)
        bb5 = np.random.rand(4)
        image4 = np.random.rand(3,125,125)
        label1 = np.random.randint(100,size=1)[0]

        sample = {
            "image_feature": [
                {
                    "image" : image1.tobytes(),
                    "shape" : shape,
                    "boundingbox_feature":[{
                        "bbox" : bb1,
                        "image_1_feature": [{
                            "image" : image4.tobytes(),
                            "shape" : shape,
                        }]
                    },
                    {
                        "bbox" : bb2
                    },
                    {
                        "bbox" : bb3,
                        "label_feature": [{
                            "label" : label1
                        }]
                    }]
                },
                {
                    "image" : image2.tobytes(),
                    "shape" : shape,
                    "boundingbox_feature":[{
                        "bbox" : bb4
                    },{
                        "bbox" : bb5
                    }]
                },
                {
                    "image" : image3.tobytes(),
                    "shape" : shape,
                    "text_1_feature":[
                        {
                            "text": text2
                        }
                    ]
                }
            ],
            "text_feature" : [
                {
                    "text": text1
                }
            ],

        }
        output.append(sample)

    with h5py.File('data_hierarchy.h5', 'w') as f:
    # Create image_feature group
        for i in range(N):
            text1 = "Foto di una nebulosa"
            text2 = "Foto infrarossi di una nebulosa"
            image1 = np.random.rand(3,125,125)
            image2 = np.random.rand(3,125,125)
            image3 = np.random.rand(3,125,125)
            shape = (3,125,125)
        
            
            bb1 = np.random.rand(4)
            bb2 = np.random.rand(4)
            bb3 = np.random.rand(4)
            bb4 = np.random.rand(4)
            bb5 = np.random.rand(4)
            image4 = np.random.rand(3,125,125)
            label1 = np.random.randint(100,size=1)[0]
            example = f.create_group(f'example_{i}')
            image_feature = example.create_group('image_feature')
            
            # Image 1
            image1 = image_feature.create_group('image1')
            image1.create_dataset('image', data=image1)  # Replace with actual image data
            
            boundingbox_feature1 = image1.create_group('boundingbox_feature')
            
            bb1 = boundingbox_feature1.create_group('bb1')
            bb1.create_dataset('bbox', data=bb1)  # Replace with actual bbox
            
            image_1_feature = bb1.create_group('image_1_feature')
            image_1_feature.create_dataset('image', data=image4)  # Replace with actual image data
            
            bb2 = boundingbox_feature1.create_group('bb2')
            bb2.create_dataset('bbox', data=bb2)  # Replace with actual bbox
            
            bb3 = boundingbox_feature1.create_group('bb3')
            bb3.create_dataset('bbox', data=bb3)  # Replace with actual bbox
            
            label_feature = bb3.create_group('label_feature')
            label_feature.create_dataset('label', data=label1)
            
            # Image 2
            image2 = image_feature.create_group('image2')
            image2.create_dataset('image', data=image2)  # Replace with actual image data
            
            boundingbox_feature2 = image2.create_group('boundingbox_feature')
            
            bb4 = boundingbox_feature2.create_group('bb4')
            bb4.create_dataset('bbox', data=bb4)  # Replace with actual bbox
            
            bb5 = boundingbox_feature2.create_group('bb5')
            bb5.create_dataset('bbox', data=bb5)  # Replace with actual bbox
            
            # Image 3
            image3 = image_feature.create_group('image3')
            image3.create_dataset('image', data=image3)  # Replace with actual image data
            
            text_1_feature = image3.create_group('text_1_feature')
            text_1_feature.create_dataset('text', data=text2)
            
            # Text feature
            text_feature = example.create_group('text_feature')
            text_feature.create_dataset('text', data=text1)


    table = pa.Table.from_pylist(output)
    df = table.to_pandas()
    df.to_csv("data.csv")
    df.to_parquet("data.parquet")

In [144]:
create_dataset(10)

In [146]:
with h5py.File('data_hierarchy.h5', 'r') as f:
    image = f["example_0/image_feature/image1/image"]
    print(image)

<HDF5 dataset "image": shape (0,), type "<f8">


In [28]:
with h5py.File('data_hierarchy.h5', 'w') as f:
    # Create image_feature group
        for i in range(10):
            text1 = "Foto di una nebulosa"
            text2 = "Foto infrarossi di una nebulosa"
            im1 = np.random.rand(3,125,125)
            im2 = np.random.rand(3,125,125)
            im3 = np.random.rand(3,125,125)
            shape = im1.shape

            print(im1.shape)
            
            bb1 = np.random.rand(4)
            bb2 = np.random.rand(4)
            bb3 = np.random.rand(4)
            bb4 = np.random.rand(4)
            bb5 = np.random.rand(4)
            im4 = np.random.rand(3,125,125)
            label1 = np.random.randint(100,size=1)[0]
            example = f.create_group(f'example_{i}')
            image_feature = example.create_group('image_feature')
            
            # Image 1
            image1 = image_feature.create_group('image1')
            tmp = image1.create_dataset('image', data=im1)  # Replace with actual image data
            
            boundingbox_feature1 = image1.create_group('boundingbox_feature')
            
            bb1 = boundingbox_feature1.create_group('bb1')
            bb1.create_dataset('bbox', data=bb1)  # Replace with actual bbox
            
            image_1_feature = bb1.create_group('image_1_feature')
            image_1_feature.create_dataset('image', data=im4)  # Replace with actual image data
            
            bb2 = boundingbox_feature1.create_group('bb2')
            bb2.create_dataset('bbox', data=bb2)  # Replace with actual bbox
            
            bb3 = boundingbox_feature1.create_group('bb3')
            bb3.create_dataset('bbox', data=bb3)  # Replace with actual bbox
            
            label_feature = bb3.create_group('label_feature')
            label_feature.create_dataset('label', data=label1)
            
            # Image 2
            image2 = image_feature.create_group('image2')
            image2.create_dataset('image', data=im2)  # Replace with actual image data
            
            boundingbox_feature2 = image2.create_group('boundingbox_feature')
            
            bb4 = boundingbox_feature2.create_group('bb4')
            bb4.create_dataset('bbox', data=bb4)  # Replace with actual bbox
            
            bb5 = boundingbox_feature2.create_group('bb5')
            bb5.create_dataset('bbox', data=bb5)  # Replace with actual bbox
            
            # Image 3
            image3 = image_feature.create_group('image3')
            image3.create_dataset('image', data=im3)  # Replace with actual image data
            
            text_1_feature = image3.create_group('text_1_feature')
            text_1_feature.create_dataset('text', data=text2)
            
            # Text feature
            text_feature = example.create_group('text_feature')
            text_feature.create_dataset('text', data=text1)

(3, 125, 125)
(3, 125, 125)
(3, 125, 125)
(3, 125, 125)
(3, 125, 125)
(3, 125, 125)
(3, 125, 125)
(3, 125, 125)
(3, 125, 125)
(3, 125, 125)


In [29]:
with h5py.File('data_hierarchy.h5', 'r') as f:
    image = f["example_0/image_feature/image1/image"][:]
    print(image)

[[[0.02707179 0.01445862 0.54346813 ... 0.62286497 0.55470985 0.99314832]
  [0.41988827 0.31134362 0.20832125 ... 0.35757614 0.11502904 0.81292584]
  [0.97571998 0.94796423 0.06255649 ... 0.85663944 0.83352975 0.21028357]
  ...
  [0.44761311 0.91980137 0.378735   ... 0.28158199 0.81048319 0.98984662]
  [0.01413412 0.47949203 0.54076516 ... 0.12205313 0.89296691 0.3178021 ]
  [0.63191732 0.67179603 0.09129387 ... 0.19293077 0.138883   0.7039817 ]]

 [[0.19812871 0.30304873 0.49585923 ... 0.83038746 0.50106728 0.62616623]
  [0.74735297 0.72644431 0.36213075 ... 0.12009977 0.34581294 0.50978539]
  [0.18570467 0.0973818  0.14433407 ... 0.41619141 0.67930133 0.45119774]
  ...
  [0.3545246  0.7060414  0.75893549 ... 0.92418294 0.30490053 0.98048477]
  [0.0856451  0.23440936 0.81240717 ... 0.95431153 0.62640134 0.76764733]
  [0.49894333 0.53208246 0.98355687 ... 0.65587854 0.92047767 0.84876315]]

 [[0.71385722 0.55195168 0.81337614 ... 0.41697092 0.84390822 0.95747555]
  [0.75551448 0.793386